'use strict';

const fs = require('fs');
const path = require('path');

const VERSION = require('../package.json').version;

const SEVERITY_ORDER = ['blocker', 'high', 'medium', 'low', 'pass', 'info'];

const SEVERITY_LABEL = {
  blocker: '[BLOCKER]',
  high:    '[HIGH]',
  medium:  '[MEDIUM]',
  low:     '[LOW]',
  pass:    '[PASS]',
  info:    '[INFO]',
};

function countBySeverity(results) {
  const counts = {};
  for (const r of results) {
    for (const issue of r.issues || []) {
      if (issue.notApplicable) continue;
      counts[issue.severity] = (counts[issue.severity] || 0) + 1;
    }
  }
  return counts;
}

function totalActionableIssues(counts) {
  return Object.entries(counts)
    .filter(([s]) => !['pass', 'info'].includes(s))
    .reduce((a, [, v]) => a + v, 0);
}

function buildMarkdown(results, config) {
  const timestamp = new Date().toISOString();
  const counts = countBySeverity(results);
  const total = totalActionableIssues(counts);
  const lines = [];

  lines.push(`# Viewport Sentinel scan report`);
  lines.push(``);
  lines.push(`| Field | Value |`);
  lines.push(`|-------|-------|`);
  lines.push(`| **URL** | \`${config.siteUrl}\` |`);
  lines.push(`| **Timestamp** | ${timestamp} |`);
  lines.push(`| **Mode** | ${config.mode}${config.debug ? ' + debug' : ''} |`);
  lines.push(`| **Devices tested** | ${results.length} |`);
  lines.push(`| **Actionable issues** | ${total} |`);
  lines.push(``);

  // Severity summary table
  lines.push(`## Severity Summary`);
  lines.push(``);
  lines.push(`| Severity | Count |`);
  lines.push(`|----------|------:|`);
  for (const s of SEVERITY_ORDER) {
    if (counts[s] !== undefined) {
      lines.push(`| ${SEVERITY_LABEL[s]} | ${counts[s]} |`);
    }
  }
  lines.push(``);

  // Device overview table
  lines.push(`## Device Overview`);
  lines.push(``);
  lines.push(`| Device | Category | Viewport | Issues | Status |`);
  lines.push(`|--------|----------|----------|-------:|--------|`);
  for (const r of results) {
    const actionable = (r.issues || []).filter(
      i => !i.notApplicable && i.severity !== 'pass' && i.severity !== 'info'
    );
    const status = r.error
      ? 'Error'
      : actionable.length === 0
      ? 'Clean'
      : `${actionable.length} issue(s)`;
    lines.push(
      `| ${r.device} | ${r.category} | ${r.viewport.width}x${r.viewport.height} | ${actionable.length} | ${status} |`
    );
  }
  lines.push(``);

  // Per-device issue details
  lines.push(`## Issues`);
  lines.push(``);

  let anyIssues = false;
  for (const r of results) {
    const actionable = (r.issues || []).filter(
      i => !i.notApplicable && i.severity !== 'pass' && i.severity !== 'info'
    );

    if (actionable.length === 0 && !r.error) continue;
    anyIssues = true;

    lines.push(`### ${r.device} (${r.viewport.width}x${r.viewport.height})`);
    lines.push(``);

    if (r.error) {
      lines.push(`> **Error during scan:** ${r.error}`);
      lines.push(``);
    }

    for (const issue of actionable) {
      const label = SEVERITY_LABEL[issue.severity] || `[${issue.severity.toUpperCase()}]`;
      lines.push(`#### ${label} ${issue.title}`);
      lines.push(``);
      lines.push(
        `**Detection method:** ${issue.method} | **Confidence:** ${issue.confidence}` +
        (issue.isHeuristic ? ' *(heuristic, not a guaranteed bug)*' : '')
      );
      lines.push(``);
      lines.push(issue.detail);
      lines.push(``);
      if (issue.suspectedCause) {
        lines.push(`**Suspected cause:** ${issue.suspectedCause}`);
        lines.push(``);
      }
      if (issue.suggestedFix) {
        lines.push(`**Suggested fix:** ${issue.suggestedFix}`);
        lines.push(``);
      }
      lines.push(`---`);
      lines.push(``);
    }
  }

  if (!anyIssues) {
    lines.push(`No actionable issues detected across all devices.`);
    lines.push(``);
  }

  lines.push(`---`);
  lines.push(``);
  lines.push(`*Generated by Viewport Sentinel v${VERSION}, ${timestamp}*`);

  return lines.join('\n');
}

async function generateReports(results, config) {
  const reportData = {
    meta: {
      url: config.siteUrl,
      timestamp: new Date().toISOString(),
      mode: config.mode,
      debug: config.debug,
      strict: config.strict,
      version: VERSION,
    },
    summary: countBySeverity(results),
    results,
  };

  const jsonPath = path.join(config.outDir, 'report.json');
  const mdPath = path.join(config.outDir, 'report.md');

  fs.writeFileSync(jsonPath, JSON.stringify(reportData, null, 2), 'utf8');
  fs.writeFileSync(mdPath, buildMarkdown(results, config), 'utf8');

  return { json: jsonPath, markdown: mdPath };
}

module.exports = { generateReports };
